language: node_js

# mvn settings
before_install: "git clone -b travis `git config --get remote.origin.url` target/travis"
script: "[ ${TRAVIS_PULL_REQUEST} = 'false' ] && mvn clean deploy --settings target/travis/settings.xml || mvn clean verify --settings target/travis/settings.xml"

node_js:
  - "4"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
install:
  - npm install
  - npm install -g grunt-cli
  - grunt

env:
  global:
    - secure: "oat6wfkHP0aqbMP/QstPNuOYjh0t70+vwvvTO6nVvC7p+fTBg6n15qBiEWIFFtnrfS/SYnS3gMOXD3UYRZnqJEoN+0o1A0nJXv2uJknG73s2XQIdVrGHYlFW4Ln2aKYN6AnfQ032U+41Gp0UvyP0N2XpqeayMpcTPBZ1zSzzDPg="
    - secure: "nOuEH0ooli8d3CbuFrBgjDhN5zKaR5xrGMp5REH7aTGqPw/WVxJwbL6X+Jx8r+Voci1HwHBeRK8ZKEQV+74Zb7XNAPmASvUYb/YvoElew8+v1f4mPrGPgZXwMx+GVkfkiYKIOx9xEQBEBTRD6sqVX/18bMYZob48HIRjF5cFTQg="